spring.application.name=CustamarCURD
spring.datasource.url=jdbc:mysql://root:VQNwUFlONPLMzYFkVdckxPmhLPZsscfm@interchange.proxy.rlwy.net:30544/railway

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update